import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("sticky booking bar reuses the reservation form and opens Guesty results in-page", async () => {
  const sticky = await readFile("app/components/StickyBookingBar.tsx", "utf8");
  const search = await readFile("app/components/BookingSearchBar.tsx", "utf8");
  const calendar = await readFile("components/ui/calendar.tsx", "utf8");
  const styles = await readFile("app/globals.css", "utf8");

  assert.match(sticky, /BookingSearchBar/);
  assert.match(sticky, /BookingResults/);
  assert.match(sticky, /popoverDirection="up"/);
  assert.match(sticky, /mobileCompact/);
  assert.match(sticky, /role="dialog"/);
  assert.match(sticky, /data-state=\{isPanelClosing \? "closing" : "open"\}/);
  assert.match(sticky, /closeTimerRef/);
  assert.doesNotMatch(sticky, /href="\/booking"/);
  assert.doesNotMatch(search, /promoCode|<Tag|togglePanel\("promo"/);
  assert.match(search, /popoverDirection\?: "up" \| "down"/);
  assert.match(search, /submitLabel\?: string/);
  assert.match(search, /mobileCompact\?: boolean/);
  assert.match(search, /lg:hidden/);
  assert.match(search, /min-height: 760px/);
  assert.match(search, /casa-zii-booking-popover/);
  assert.match(search, /isPopoverClosing/);
  assert.match(search, /requestPopoverClose/);
  assert.match(search, /casa-zii-booking-popover-exit/);
  assert.match(search, /calendarMonths === 2/);
  assert.match(search, /calendarIsCompact\s*\? "p-0 \[--cell-size:2\.125rem\]"/);
  assert.match(search, /"px-4 pt-4 max-lg:px-4 max-lg:pt-4 lg:px-6 lg:pt-6"/);
  assert.match(search, /calendarMonths === 2\s*\? "w-full lg:w-\[22\.75rem\]/);
  assert.match(search, /mx-auto w-\[min\(100%,calc\(var\(--cell-size\)\*7\)\)\]/);
  assert.match(search, /max-lg:border-spacing-y-1/);
  assert.match(search, /months:\s*\n?\s*"relative flex flex-col gap-8 md:flex-row lg:gap-14 max-lg:gap-3 rdp-months"/);
  assert.match(search, /nav: "absolute inset-x-0 top-0 z-10 flex w-full items-center justify-between rdp-nav"/);
  assert.match(search, /\[--cell-size:2\.25rem\]/);
  assert.match(search, /lg:w-\[22\.75rem\]/);
  assert.match(search, /min-h-\[52px\]/);
  assert.match(search, /max-lg:max-h-\[min\(calc\(100dvh-10rem\),34rem\)\]/);
  assert.doesNotMatch(search, /lg:min-h-\[34rem\]/);
  assert.match(search, /z-10 flex w-full items-center justify-between rdp-nav/);
  assert.match(search, /grid grid-rows-\[auto_auto\]/);
  assert.doesNotMatch(search, /week: "mt-4 flex w-full rdp-week"/);
  assert.match(calendar, /month_grid: cn\(\s*"w-full table-fixed border-separate border-spacing-y-4"/);
  assert.doesNotMatch(calendar, /\btable: "w-full table-fixed/);
  assert.match(calendar, /month: cn\("w-full"/);
  assert.doesNotMatch(calendar, /month: cn\("flex flex-col/);
  assert.match(calendar, /weekdays: cn\("table-row"/);
  assert.match(calendar, /week: cn\("table-row"/);
  assert.doesNotMatch(calendar, /week: cn\("flex/);
  assert.match(styles, /casaZiiBookingPanelEnter/);
  assert.match(styles, /transform-origin: center bottom/);
  const panelExit = styles.match(/@keyframes casaZiiBookingPanelExit\s*\{([\s\S]*?)\n\}\n\n\.casa-zii-booking-panel/);
  assert.ok(panelExit, "the booking-panel exit animation should remain defined");
  assert.doesNotMatch(panelExit[1], /border-radius/);
  assert.match(styles, /casaZiiBookingScrimEnter/);
  assert.match(styles, /casaZiiBookingPopoverEnter/);
  assert.match(styles, /casaZiiBookingPopoverExitUp/);
  assert.match(styles, /casa-zii-booking-popover-exit/);
  assert.match(styles, /prefers-reduced-motion/);
});
